### ISSUE TITLE
Change `problems/` files to header-only?

### ISSUE THREAD

**Issue by rcurtin** [mlpack/ensmallen#1]
Right now we have .cpp files in `ensmallen_bits/problems/`; we could inline the methods and make them `.hpp` files, which would let us keep the library as header-only.  Any thoughts?  If everyone agrees I can go ahead and do this.

**Comment by rcurtin** [comment]
I guess another idea is to move the `problems/` directory to the `tests/` folder.

**Comment by conradsnicta** [comment]
As I'm still getting familiar with the codebase, could you explain what is the intent of the code in the `problems` directory?

**Comment by zoq** [comment]
The ``problems`` directory  contains some optimization test problems like the booth function.

**Comment by zoq** [comment]
I think it's reasonable to move the directory to the ``tests/`` folder.

**Comment by conradsnicta** [comment]
@zoq - ok, I'll move the files once I'm done with the initial conversion from boost to catch.

**Comment by rcurtin** [comment]
This is done now; all the problems are header only.
