### ISSUE TITLE
Infinite loop bug in SGD

### ISSUE THREAD

**Issue by greatsharma** [mlpack/ensmallen#104]
When we run SGD with 0 batch size then the loop goes infinite. Although it is very stupid thing to use 0 batch size but user can accidentally set batch size to 0 ( as I did it accidentally ). And as training on very large data set and complex machine learning models do take large amount of time so if an user accidentally set batch size 0 for such situation then they may think that the optimizer is taking so long time probably due to large data set and complex model but indeed they were stuck in a infinite loop and were not aware.

And if we set batch size to 0 then logically our optimizer shouldn't do anything i.e., it will not update the iterate ( initial points given by user ) and the overallObjective return by the optimizer is the value of the function which is to be optimized at that initial point given by the user.

Apart from this as software engineering tells us that while testing we should handle such boundary conditions.

**Comment by greatsharma** [comment]
This issue is solved in #105.

**Comment by rcurtin** [comment]
Agreed, it would be useful to catch this condition.  Thanks for looking into it.

**Comment by zoq** [comment]
Personally, I find it difficult to draw the line between what should be checked and what not, as you pointed out, using a batch size of 0 doesn't make much sense. Also, I think we can create a bunch of optimizer parameter combinations that will trigger a similar behavior.

**Comment by greatsharma** [comment]
@zoq I do agree with your point but I mentioned it just because I stuck in it accidentally and after few minutes when I close the execution and look closer to sgd class then I realised this. But maybe user don't look at the sgd class and they just use mlpack for developing purpose and not for contribution. Rest as mentioned by @rcurtin in #105 I do throw an exception for that.
