### ISSUE TITLE
Obtain the hessian matrix at the optimal point

### ISSUE THREAD

**Issue by mangelett** [mlpack/ensmallen#107]
Hi,

After having solved an optimization problem, is it a way to estimate the gradient and the hessian matrix at the optimum point it the function does not implement  the gradient nor the hessian?

Best Regards

**Comment by rcurtin** [comment]
Well, if the function you're optimizing has an `Evaluate()` and `Gradient()` method, you can just call `Gradient()` to compute the gradient at the final returned matrix from `Optimize()`.  For the Hessian you'd have to implement that yourself for the `FunctionType` you are optimizing, but you could just call that using the returned matrix from `Optimize()` too. :+1:

Let me know if I can clarify my comments.
