### ISSUE TITLE
error: using namespace ens

### ISSUE THREAD

**Issue by merria28** [mlpack/ensmallen#110]
I installed "ensmallen" successfully. Then an error occur when i calling by "using namespace ens".
The error is following:
Error	C2664	'arma::Mat<double>::Mat(arma::Mat<double> &&)': cannot convert argument 1 from 'arma::uword' to 'const arma::SizeMat &' 

at  line 92 in file "atoms.hpp" :
arma::mat gradient(size(x));

**Comment by conradsnicta** [comment]
Try the following workaround:

    arma::mat gradient(arma::size(x));

Note that MSVC is full of bugs. For any real work, I suggest using a proper compiler like gcc or clang.

**Comment by merria28** [comment]
@conradsnicta  thanks a lot.  This issue is solved.
