### ISSUE TITLE
 `shuffle` parameter in `spsa` is not used

### ISSUE THREAD

**Issue by coatless** [mlpack/ensmallen#114]
#### Issue description

The `shuffle` parameter in `spsa` is not used.

```
 ../inst/include/ensmallen_bits/spsa/spsa.hpp:120:8: 
warning: private field 'shuffle' is not used [-Wunused-private-field]
  bool shuffle;
       ^
```

#### Your environment

 * version of ensmallen: 1.15.0
 * operating system: macOS
 * compiler: clang 7.0.0
 * version of Armadillo: 9.400
 * any other environment information you think is relevant:

#### Steps to reproduce

Compile ensmallen.

**Comment by rcurtin** [comment]
Since #115 is merged, this is now solved.  Thanks for the PR. :+1:
