### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by coatless** [mlpack/ensmallen#122]
When pulling from [`HISTORY.md`](https://github.com/mlpack/ensmallen/blob/master/HISTORY.md), the release notes:

1. miss the "code name" that can be found in `ensmallen.hpp` and [GitHub release page](https://github.com/mlpack/ensmallen/releases).
2. miss hard links to the PR, e.g. `#86` -> `[#86](https://github.com/mlpack/ensmallen/pull/86)`

Would it be possible to always include these components?

**Comment by rcurtin** [comment]
Oh, I see, that's easy enough to do.  Let me manually make those changes now.  I don't think it's worth issuing 1.16.1 with just changes to HISTORY.md, but we can make sure that happens in the future.  Does that sound good?

**Comment by coatless** [comment]
Sounds good! I agree, there is no need to release these history changes as 1.16.1.

**Comment by rcurtin** [comment]
Fixed in #125.  I'll make sure that HISTORY.md follows this format in the future.  To make your life easier, should we do this for mlpack also?

**Comment by coatless** [comment]
@rcurtin I'm not sure how important that would be as the `RcppMLPACK` bridge relies on the system-specific version of `MLPACK` installed whereas the `RcppEnsmallen` package  distributes the header-only library.

**Comment by rcurtin** [comment]
Ah, got it, thanks for the clarification. :+1:
