### ISSUE TITLE
Callback with Ann

### ISSUE THREAD

**Issue by shrit** [mlpack/ensmallen#130]
Hello,

Thanks for releasing ensmallen 2.10.0 with Callback PR, it is really a great work.
It is possible to show an example about how to use the callbacks with ann? I am not sure if I understood well the ffn class, but It seems that the train function does not take in account the callbacks yet, since it is calling `optimizer.Optimize(*this, parameter)`

Best regards,

**Comment by rcurtin** [comment]
Exactly, the mlpack code isn't updated yet.  You could locally modify your copy so that `Train()` takes callbacks as parameters, for instance.  I hope that we can get the callback support in the mlpack ANN code soon for sure. :+1:

**Comment by zoq** [comment]
I have opened https://github.com/mlpack/mlpack/issues/2013 which also shows the modifications of the ``FFN`` class. Let's discussion further details over there.
