### ISSUE TITLE
Testing Smashing Autobuilders

### ISSUE THREAD

**Issue by barak** [mlpack/ensmallen#132]
#### Issue description

The Debian ensmallen package is automatically built (compiled) on many architectures. The build process runs the test scripts. Everything works fine on some architectures (amd64, say) albeit with a rather large amount of time required for the test phase. But on some other architectures (i386, see https://buildd.debian.org/status/fetch.php?pkg=ensmallen&arch=i386&ver=2.10.0-1&stamp=1568047415 for details) the test phase exceeds some resource limitation and the build is terminated.

I could just turn off testing, but that seems wrong. Best would be if the test phase were much faster, or if there was a fast test run by default with the current extremely time consuming test run only if some extra option is given.

#### Your environment

 * version of ensmallen: 2.10.0
 * operating system: Debian/unstable
 * compiler: GCC 9.x

#### Steps to reproduce

Clone https://github.com/barak/ensmallen, go to tag debian/2.10.0-1, run `fakeroot debian/rules binary` on a crappy machine with a low ulimit set.

#### Expected behavior

ensmallen sucessfully autobuilt on all sorts of weird architectures.

#### Actual behavior

https://buildd.debian.org/status/package.php?p=ensmallen

**Comment by zoq** [comment]
Thanks for the report, I can see a similar issue in the matrix build: http://ci.mlpack.org/view/ensmallen/job/docker%20ensmallen%20nightly%20build/

will take a closer look, unless somebody else likes to dive into the issue.

**Comment by conradsnicta** [comment]
I think the underlying problem is that the test suite is compiled without optimisation (ie. sans -O2), so once it's built it takes forever to run.

**Comment by zoq** [comment]
@barak Is it possible to manually test against a branch, e.g. https://github.com/mlpack/ensmallen/pull/135?

**Comment by barak** [comment]
I've heard rumours that it might be, but have not tried myself.

(Seriously, I can log into a development machine dedicated to porting to some architecture and give it a shot, especially if you tell me which architecture(s) you'd recommend.)

**Comment by zoq** [comment]
Great, thanks. Any platform that timed out will do, e.g. i386 - Debian sid.

**Comment by zoq** [comment]
@barak We just release ensmallen 2.10.3: https://github.com/mlpack/ensmallen/releases/tag/2.10.3 hopefully that will  fix the issue you reported above.

**Comment by barak** [comment]
Uploaded the 2.10.3, and the autobuilders encountered issues on some architectures. See https://buildd.debian.org/status/package.php?p=ensmallen which already shows problems on armel, s390x, hurd-i386. Lots of `void*` alignment warnings, not sure if those are relevant.

This is on armel:
```
...
Test project /<<PKGBUILDDIR>>/obj-arm-linux-gnueabi
    Start 1: ensmallen_tests
E: Build killed with signal TERM after 150 minutes of inactivity
```
This is on s360x:
```
...
make[2]: Leaving directory '/<<PKGBUILDDIR>>/obj-s390x-linux-gnu'
/usr/bin/cmake -E cmake_progress_start /<<PKGBUILDDIR>>/obj-s390x-linux-gnu/CMakeFiles 0
make[1]: Leaving directory '/<<PKGBUILDDIR>>/obj-s390x-linux-gnu'
   dh_auto_test -a
	cd obj-s390x-linux-gnu && make -j2 test ARGS\+=-j2
make[1]: Entering directory '/<<PKGBUILDDIR>>/obj-s390x-linux-gnu'
Running tests...
/usr/bin/ctest --force-new-ctest-process -j2
Test project /<<PKGBUILDDIR>>/obj-s390x-linux-gnu
    Start 1: ensmallen_tests
1/1 Test #1: ensmallen_tests ..................***Failed  322.17 sec
ensmallen version: 2.10.3 (Fried Chicken)
armadillo version: 9.600.5 (Napa Invasion)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ensmallen_tests is a Catch v2.4.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
EveSGDFunction
-------------------------------------------------------------------------------
/<<PKGBUILDDIR>>/tests/eve_test.cpp:23
...............................................................................

/<<PKGBUILDDIR>>/tests/eve_test.cpp:32: FAILED:
  REQUIRE( coordinates(1) == Approx(0.0).margin(0.1) )
with expansion:
  -0.1271843391 == Approx( 0.0 )

===============================================================================
test cases:   266 |   265 passed | 1 failed
assertions: 12391 | 12390 passed | 1 failed



0% tests passed, 1 tests failed out of 1

Total Test time (real) = 322.17 sec

The following tests FAILED:
	  1 - ensmallen_tests (Failed)
Errors while running CTest
make[1]: *** [Makefile:100: test] Error 8
```

**Comment by barak** [comment]
Also i386
```
...
/<<PKGBUILDDIR>>/tests/callbacks_test.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____46()’:
/<<PKGBUILDDIR>>/tests/callbacks_test.cpp:397:28: warning: unsigned conversion from ‘long long int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘10000000000’ to ‘1410065408’ [-Woverflow]
  397 |   StandardSGD s(0.0003, 1, 10000000000, -10);
      |                            ^~~~~~~~~~~
/<<PKGBUILDDIR>>/tests/callbacks_test.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____54()’:
/<<PKGBUILDDIR>>/tests/callbacks_test.cpp:473:28: warning: unsigned conversion from ‘long long int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘10000000000’ to ‘1410065408’ [-Woverflow]
  473 |   StandardSGD s(0.0003, 1, 10000000000, -100, true);
      |                            ^~~~~~~~~~~
...

Running tests...
/usr/bin/ctest --force-new-ctest-process -j4
Test project /<<PKGBUILDDIR>>/obj-i686-linux-gnu
    Start 1: ensmallen_tests
1/1 Test #1: ensmallen_tests ..................***Failed  2550.09 sec
ensmallen version: 2.10.3 (Fried Chicken)
armadillo version: 9.600.5 (Napa Invasion)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ensmallen_tests is a Catch v2.4.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
RosenbrockFunctionFloatTest
-------------------------------------------------------------------------------
/<<PKGBUILDDIR>>/tests/lbfgs_test.cpp:41
...............................................................................

/<<PKGBUILDDIR>>/tests/lbfgs_test.cpp:54: FAILED:
  REQUIRE( coords(1) == Approx(1.0).epsilon(1e-7) )
with expansion:
  1.0f == Approx( 1.0 )

-------------------------------------------------------------------------------
Johnson844LovaszThetaFMatSDP
-------------------------------------------------------------------------------
/<<PKGBUILDDIR>>/tests/lrsdp_test.cpp:136
...............................................................................

/<<PKGBUILDDIR>>/tests/lrsdp_test.cpp:161: FAILED:
  REQUIRE( finalValue == Approx(-14.0).epsilon(0.1) )
with expansion:
  nanf == Approx( -14.0 )

===============================================================================
test cases:   266 |   264 passed | 2 failed
assertions: 11281 | 11279 passed | 2 failed



0% tests passed, 1 tests failed out of 1

Total Test time (real) = 2550.09 sec

The following tests FAILED:
	  1 - ensmallen_tests (Failed)
Errors while running CTest
...
```

**Comment by zoq** [comment]
Will see if I can reproduce the issue and open a PR.

**Comment by rcurtin** [comment]
I had this issue while doing Fedora packaging also; some of the ensmallen tests are flaky.  I looked through the historical Jenkins builds and came up with these (semi-regular) failing tests:

`NesterovMomentumSGDSpeedUpTestFunction` - http://ci.mlpack.org/job/docker%20ensmallen%20nightly%20build/64/armadillo_version=armadillo-8.600.1,compiler_version=llvm-3.5.2-patch,label=docker/testReport/junit/ensmallen_tests/global/NesterovMomentumSGDSpeedUpTestFunction/

`DELogisticRegressionFMatTest` - http://ci.mlpack.org/job/docker%20ensmallen%20nightly%20build/50/armadillo_version=armadillo-8.600.1,compiler_version=gcc-6.1.0,label=docker/testReport/junit/ensmallen_tests/global/DELogisticRegressionFMatTest/

`DELogisticRegressionTest` - http://ci.mlpack.org/job/docker%20ensmallen%20nightly%20build/47/armadillo_version=armadillo-9.600.6,compiler_version=llvm-8.0.1,label=docker/testReport/junit/ensmallen_tests/global/DELogisticRegressionTest/

This is in addition to the errors listed by @barak.  (Actually that `RosenbrockFunctionFloatTest` just looks like it should be `REQUIRE( coords(1) == Approx(1.0f).epsilon(1e-7) );`, which is an easy fix.

I'll try to handle the three tests above plus `RosenbrockFunctionFloatTest` shortly.
