### ISSUE TITLE
Collapsible code examples in documentation

### ISSUE THREAD

**Issue by rcurtin** [mlpack/ensmallen#139]
#### Problem location

The ensmallen documentation is full of big example programs like the one at the bottom of this section:
http://ensmallen.org/docs.html#differentiable-functions

#### Description of problem

These examples are kind of hard to scroll through when perusing the documentation.  It would be really cool if we had a way to make these collapsible.  The answer might actually be in the ensmallen.org repo, but I am not sure if Markdown has support for collapsible code snippets or anything.  In any case, I haven't looked into it and don't have time to do it now, but thought it would be a really nice feature so I opened it as an issue in case anyone is interested.  If not I will get around to it eventually. :-D

Probably it's not necessary to have everything be collapsible, only the "long" example programs.

**Comment by coatless** [comment]
`markdown` lacks support for that. However, you can add in some custom js/css to collapse the code block. 

Alternatively, you can also go the github approach with `details` and `summary` tags. c.f. https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab

````
<details>
  <summary>Click to expand!</summary>

```md
## Heading
1. A numbered
2. list
   * With some
   * Sub bullets
```

</details>
````

<details>
  <summary>Click to expand!</summary>

```md
## Heading
1. A numbered
2. list
   * With some
   * Sub bullets
```

</details>

**Comment by zoq** [comment]
I like the `details` and `summary` solution.

**Comment by jeffin143** [comment]
@zoq , @rcurtin If you are ok with @coatless  suggestion , I can handle it, Exam week ahead, Would probably work on this. :)

Or should we wait for some other ideas ?

**Comment by rcurtin** [comment]
@jeffin143 that sounds fine to me if you want to do it. :+1:

**Comment by zoq** [comment]
That would be great, excited to see the result.

**Comment by rcurtin** [comment]
Since #140 is merged, I think we can close this. :+1:
