### ISSUE TITLE
using std namespace in header files

### ISSUE THREAD

**Issue by aabghari** [mlpack/ensmallen#146]
#### Issue description

There are several header files with `using namespace std;`. This is a bad practise because it pollutes the application namespace when including those header files in your application. 
Here is the list of the header files with such a definition:

ensmallen_bits/problems/ackley_function_impl.hpp
ensmallen_bits/problems/beale_function_impl.hpp
ensmallen_bits/problems/cross_in_tray_function_impl.hpp
ensmallen_bits/problems/goldstein_price_function_impl.hpp
ensmallen_bits/problems/himmelblau_function_impl.hpp
ensmallen_bits/problems/holder_table_function_impl.hpp
ensmallen_bits/problems/levy_function_n13_impl.hpp
ensmallen_bits/problems/schaffer_function_n2_impl.hpp
ensmallen_bits/problems/schaffer_function_n4_impl.hpp
ensmallen_bits/problems/three_hump_camel_function_impl.hpp

#### Your environment

 * version of ensmallen: 2.10.4
 * operating system: Linux Debian 10
 * compiler: gcc 8.3.0
 * version of Armadillo:
 * any other environment information you think is relevant:

#### Steps to reproduce

include ensmallen header file in the code

#### Expected behavior

Including ensmallen in your code must not make std namespace to be used by default.

#### Actual behavior

Including ensmallen in your code causes std namespace to be used by default.

**Comment by rcurtin** [comment]
You're right, that's a significant issue.  I opened a PR in #147 to fix the issue.  Thanks for the report!

**Comment by zoq** [comment]
Fixed in https://github.com/mlpack/ensmallen/pull/147.
