### ISSUE TITLE
add the jenkins valgrind memory checker 

### ISSUE THREAD

**Issue by birm** [mlpack/ensmallen#168]
Since we aren't monitoring memory now, we recently had a memory leak (#167). It's probably a good idea to copy the mlpack [valgrind ci test](http://ci.mlpack.org/job/pull-requests%20mlpack%20memory/)  to the ensmallen repo too.

**Comment by gaurav-singh1998** [comment]
Hi, @birm I would like to take up this issue. Can you guide me on how to move forward with it?

**Comment by birm** [comment]
I'm not sure this is a great first issue, in that it can't be finished without configuring the jenkins server directly. Though, I suppose you could add it to travis or something similar as a second part of the test.

If you still want to work on it. I'd recommend setting up CI testing on your fork and having it run valgrind somehow. Some of the code used by jenkins to memory check mlpack is [here](https://github.com/mlpack/jenkins-conf/tree/master/memory).

**Comment by gaurav-singh1998** [comment]
@birm, Thanks for replying I will move forward with this issue and will message you here if anything is required. Is it okay?

**Comment by rcurtin** [comment]
Yeah, I think this is one that only Jenkins admins can do, unfortunately.

**Comment by gaurav-singh1998** [comment]
Okay, @rcurtin so I guess I should leave this and look at other issues to solve?

**Comment by rcurtin** [comment]
@gaurav-singh1998 yeah, try other issues.  I think I may have just set this up correctly on http://ci.mlpack.org/ but we'll see as time goes on. :+1:  I'll close this issue once it works right. :)

**Comment by rcurtin** [comment]
Ah, I'd forgotten close this, thanks @birm. :+1:
