### ISSUE TITLE
Add more multi-objective optimizers!

### ISSUE THREAD

**Issue by say4n** [mlpack/ensmallen#176]
PR #149 implements the NSGA2 optimizer, this issue is a prompt to add other multi-objective optimizers like:
- [ ] [Directed Search Domain](http://personalpages.manchester.ac.uk/staff/S.Utyuzhnikov/Papers/DSDreprint.pdf)
- [ ] [Successive Pareto Optimization](https://doi.org/10.1137%2F080729013)
- [ ] [PGEN](https://doi.org/10.1118%2F1.2335486)
etc.

More information on the various methods of multi-objective optimization can be found [here](https://en.wikipedia.org/wiki/Multi-objective_optimization)!

**Comment by UtR491** [comment]
I would like to try implement [MOEA/D](https://ieeexplore.ieee.org/document/4358754), nobody is on it right? Or is there something more important which can (or has to) be implemented first?

**Comment by madhavshah49** [comment]
Hey there how should we proceed on this issue?

**Comment by say4n** [comment]
@madhavshah49 a good place to start would be [this PR](https://github.com/mlpack/ensmallen/pull/149) adding multi-objective optimisation and [this subsequent PR](https://github.com/mlpack/ensmallen/pull/210) that attempted to add MOEA/D based on the previous PR. Have fun! :)

**Comment by madhavshah49** [comment]
@say4n thank you for the suggetions I shall start from there

**Comment by shikharjan** [comment]
also what algorithm would be easier to use?

**Comment by shikharjan** [comment]
@say4n if you could tell me the mentioned things above

**Comment by say4n** [comment]
@shikharjan I haven't gone through the implementation/papers of other algorithms on the list so I can't really speak of the ease of use/implementation, keep in mind that the list is only indicative of a direction, feel free to choose any other MOO algorithm that you are comfortable working on!

As far as building on MacOS is concerned, I have had success using [homebrew](https://brew.sh) to install the dependencies as listed [on this page](https://www.mlpack.org/doc/stable/doxygen/build.html). Post that, running cmake, followed my make should compile the ensmallen unit tests for you. 

Hope this helps, waiting for your PR! :)

**Comment by IWNMWE** [comment]
Hey @say4n I was interested in taking this up as my GSoC '24 proposal idea and wanted to know if along with some new algorithms for moo I can also aim to implement NSGA-III / R-NSGA-II.
