### ISSUE TITLE
Use Eigen as backend instead of armadillo.

### ISSUE THREAD

**Issue by kilasuelika** [mlpack/ensmallen#208]
I want to use template library **Eigen** as backend. I think it's necessary to modify source. How can I start?

**Comment by rcurtin** [comment]
Hi @kilasuelika, this would actually be a very seriously involved task.  ensmallen is written for Armadillo or for other linear algebra libraries that implement Armadillo's API.  I really wouldn't recommend doing that.

Instead, if you have an Eigen matrix and you want to use ensmallen, you may be better suited by making an Armadillo matrix that is an alias of the Eigen matrix's memory.  Here is an example:

```
MatrixXf matA(2, 2);
matA << 1, 2, 3, 4;

// Now wrap matA.
// See the "advanced constructors" here:
// http://arma.sourceforge.net/docs.html#Mat
arma::mat wrappedEigenMatrix(matA.data(), matA.rows(), matA.cols(), false, true).
```

Then you could use `wrappedEigenMatrix`, and if its values are modified, those changes will be reflected in `matA` too.  I hope that this is helpful.  I haven't tried it, but this should work just fine and you should be able to adapt it to your needs.  Let me know if I can clarify anything. :+1:

**Comment by kilasuelika** [comment]
> Hi @kilasuelika, this would actually be a very seriously involved task. ensmallen is written for Armadillo or for other linear algebra libraries that implement Armadillo's API. I really wouldn't recommend doing that.
> 
> Instead, if you have an Eigen matrix and you want to use ensmallen, you may be better suited by making an Armadillo matrix that is an alias of the Eigen matrix's memory. Here is an example:
> 
> ```
> MatrixXf matA(2, 2);
> matA << 1, 2, 3, 4;
> 
> // Now wrap matA.
> // See the "advanced constructors" here:
> // http://arma.sourceforge.net/docs.html#Mat
> arma::mat wrappedEigenMatrix(matA.data(), matA.rows(), matA.cols(), false, true).
> ```
> 
> Then you could use `wrappedEigenMatrix`, and if its values are modified, those changes will be reflected in `matA` too. I hope that this is helpful. I haven't tried it, but this should work just fine and you should be able to adapt it to your needs. Let me know if I can clarify anything. 👍

Thank you so much. I like Eigen because it's a template library so that I can use it directly on my SoC without an OS. I have created a fork [ensmallen-eigen](https://github.com/kilasuelika/ensmallen-eigen). It looks like that there are 3 tasks to achieve my goal:
1. Remove checks  on function API for simplicity such as `CheckFunctionTypeAPI`, `RequireFloatingPointType`.
2. Rewrite `MatTypeTraits`.
3. Rewrite API calls of matrices. For example, `dot(x,y)` in Armadillo == `x.dot(y)` in Eigen.

**Comment by kilasuelika** [comment]
> Hi @kilasuelika, this would actually be a very seriously involved task. ensmallen is written for Armadillo or for other linear algebra libraries that implement Armadillo's API. I really wouldn't recommend doing that.
> 
> Instead, if you have an Eigen matrix and you want to use ensmallen, you may be better suited by making an Armadillo matrix that is an alias of the Eigen matrix's memory. Here is an example:
> 
> ```
> MatrixXf matA(2, 2);
> matA << 1, 2, 3, 4;
> 
> // Now wrap matA.
> // See the "advanced constructors" here:
> // http://arma.sourceforge.net/docs.html#Mat
> arma::mat wrappedEigenMatrix(matA.data(), matA.rows(), matA.cols(), false, true).
> ```
> 
> Then you could use `wrappedEigenMatrix`, and if its values are modified, those changes will be reflected in `matA` too. I hope that this is helpful. I haven't tried it, but this should work just fine and you should be able to adapt it to your needs. Let me know if I can clarify anything. 👍

I have a question that whether `function.hpp` and `function/*.hpp` really play a role in optimization process. Can I just remove them totally?

**Comment by rcurtin** [comment]
This is such a huge refactoring that I can't really assist in saying exactly what needs to be done.  It basically boils down to a whole rewrite of the entire library.

I'd really urge you to consider whether you can just use Armadillo for your task instead of Eigen, or at least an Eigen matrix wrapped in Armadillo.  Note that you don't need to link against LAPACK or BLAS if the optimization technique you are using does not use any decompositions.

**Comment by kilasuelika** [comment]
> This is such a huge refactoring that I can't really assist in saying exactly what needs to be done. It basically boils down to a whole rewrite of the entire library.
> 
> I'd really urge you to consider whether you can just use Armadillo for your task instead of Eigen, or at least an Eigen matrix wrapped in Armadillo. Note that you don't need to link against LAPACK or BLAS if the optimization technique you are using does not use any decompositions.

Thank you. I will consider your advice.

**Comment by conradsnicta** [comment]
@kilasuelika Armadillo can be used as a pure template library as well. Compile your code with the macros `ARMA_DONT_USE_BLAS` and `ARMA_DONT_USE_LAPACK` enabled. Example:

    g++ prog.cpp -o prog -O3 -DARMA_DONT_USE_BLAS -DARMA_DONT_USE_LAPACK -I/home/blah/armadillo-9.900.2/include 

change `/home/blah/armadillo-9.900.2/include` to wherever you have unpacked the armadillo archive.

Alternatively, you can define these macros at the top of your code, before the `#include <armadillo>` statement (and before `#include <ensmallen.hpp>`).  Example:
    
    #define ARMA_DONT_USE_BLAS
    #define ARMA_DONT_USE_LAPACK
    #include <armadillo>

More info available at the [FAQ page](http://arma.sourceforge.net/faq.html).

**Comment by kilasuelika** [comment]
> @kilasuelika Armadillo can be used as a pure template library as well. Compile your code with the macros `ARMA_DONT_USE_BLAS` and `ARMA_DONT_USE_LAPACK` enabled. Example:
> 
> ```
> g++ prog.cpp -o prog -O3 -DARMA_DONT_USE_BLAS -DARMA_DONT_USE_LAPACK -I/home/blah/armadillo-9.900.2/include 
> ```
> 
> change `/home/blah/armadillo-9.900.2/include` to wherever you have unpacked the armadillo archive.
> 
> Alternatively, you can define these macros at the top of your code, before the `#include <armadillo>` statement (and before `#include <ensmallen.hpp>`). Example:
> 
> ```
> #define ARMA_DONT_USE_BLAS
> #define ARMA_DONT_USE_LAPACK
> #include <armadillo>
> ```
> 
> More info available at the [FAQ page](http://arma.sourceforge.net/faq.html).

Wow it's really good. Thank you so much!
