### ISSUE TITLE
HISTORY.md version update not included in the tag build

### ISSUE THREAD

**Issue by coatless** [mlpack/ensmallen#222]
Hi all,

I'm working on automating a PR based on an upstream change in `ensmallen`'s codebase (c.f. coatless/rcppensmallen#30). One part that I noticed is the `.tar.gz` made available under the release tag does not include the appropriate `HISTORY.md` version update.

For instance:

https://raw.githubusercontent.com/mlpack/ensmallen/2.14.1/HISTORY.md

Gives:

```md
### ensmallen ?.??.?: "???"
###### ????-??-??
 * Fix release script (remove hardcoded information, trim leading whitespaces
   introduced by `wc -l` in MacOS)
    ([#216](https://github.com/mlpack/ensmallen/pull/216),
     [#220](https://github.com/mlpack/ensmallen/pull/220)).

 * Adjust tolerance for AugLagrangian convergence based on element type
   ([#217](https://github.com/mlpack/ensmallen/pull/217)).
```

Only in a later commit is the information passed on:

https://raw.githubusercontent.com/mlpack/ensmallen/9d3fc459ce34eefd969dc0843d55c619b13e4b6e/HISTORY.md

```md
### ensmallen 2.14.1: "No Direction Home"
###### 2020-08-19
```

It's a minor inconvenience to substitute this in as unreleased version is kept; however, it would be nice for the `.tar.gz` associated with the release tag to have an up-to-date `HISTORY.md` file.

**Comment by coatless** [comment]
@rcurtin I didn't realize but the version information propagation into `ens_version.hpp` is also broke. The tagged build shows 2.14.0 -- not v2.14.1.

Tagged version: https://github.com/mlpack/ensmallen/blob/2.14.1/include/ensmallen_bits/ens_version.hpp#L15-L19

```cpp
#define ENS_VERSION_MAJOR 2
// The minor version is two digits so regular numerical comparisons of versions
// work right.  The first minor version of a release is always 10.
#define ENS_VERSION_MINOR 14
#define ENS_VERSION_PATCH 0
```

Later version: 

https://github.com/mlpack/ensmallen/blob/9d3fc459ce34eefd969dc0843d55c619b13e4b6e/include/ensmallen_bits/ens_version.hpp#L15-L19

**Comment by rcurtin** [comment]
Exactly, the mlpack-bot release is using `HEAD~2` when it should be using `HEAD~1` for the tagged release.  This is because there is no merge commit when a rebase is done, so I miscounted by one.  Next release hopefully it should be fixed---sorry for the inconvenience!  I'll leave this issue open until we can prove that the release is right. :)

**Comment by coatless** [comment]
@rcurtin Thanks for fixing it! From the 2.14.2 release, the version information and history.md entries have been resolved. 🎉 

https://github.com/mlpack/ensmallen/compare/2.14.2...master
