### ISSUE TITLE
VCPKG Version Out of Date

### ISSUE THREAD

**Issue by Blakjak88** [mlpack/ensmallen#227]
I installed ensmallen using vcpkg but discovered that the "upgraded" version is quite out of date. 

vcpkg installs 2.11.2 

Latest version is 2.14.2

I found this problem as I could not get my code to compile with EarlyStopAtMinLoss using a callback function. When I checked the header file there was no callback function constructor.

I manually changed the version number in my vcpkg CONTROL file but should this not be taken care of automatically with every new release?

**Comment by rcurtin** [comment]
Hey @Blakjak88, thanks for the report.  I think maybe this should be reported to the vcpkg repository: https://github.com/microsoft/vcpkg

For instance, here's the issue where someone originally requested ensmallen to be added to vcpkg: https://github.com/microsoft/vcpkg/issues/5015

I've asked them to bump the version of mlpack before; they're typically pretty responsive and helpful. :+1:

**Comment by Blakjak88** [comment]
I reported it to VCPKG about a week ago. Not sure if it is updated yet.

**Comment by rcurtin** [comment]
Thanks for doing that @Blakjak88! Do you have a link to the bug report? :+1:

**Comment by Blakjak88** [comment]
@rcurtin  Here is the link to the mlpack update request.

https://github.com/microsoft/vcpkg/issues/13877

**Comment by Blakjak88** [comment]
@rcurtin  ... and here is the request for ensmallen update.

https://github.com/microsoft/vcpkg/issues/13879
