### ISSUE TITLE
[Question] Nelder-Mead

### ISSUE THREAD

**Issue by alexhallam** [mlpack/ensmallen#229]
I am looking for a Nelder-Mead optimization implementation. I saw it mentioned here https://www.mlpack.org/papers/mlpack2011.pdf  I was hoping to get pointed in the right direction.

**Comment by rcurtin** [comment]
Hey @alexhallam, various refactorings over the years meant that our Nelder-Mead implementation isn't actually a part of the library. :(  It would actually be pretty easy to implement, and so I'm tempted to just do it now, but I think I have too many things going on.  Maybe we should leave this issue open as a feature request?

**Comment by alexhallam** [comment]
It looks like [nlopt](https://github.com/stevengj/nlopt) has a Nelder-Mead implimentation. I am not sure how much rework needs to be done or what the benifits are of using ensmallen over nlopt.

**Comment by zoq** [comment]
I haven't looked at nlopt so I can't comment about the pros at this point, but I have some time over the week and NM was on my list anyway, so I will give this a shot.

**Comment by zoq** [comment]
Just opened https://github.com/mlpack/ensmallen/pull/231 which implements Nelder-Mead.
