### ISSUE TITLE
conda R ensmallen package

### ISSUE THREAD

**Issue by zoq** [mlpack/ensmallen#235]
I'm trying to build mlpack with the R bindings enabled using conda, looks like there is are recent versions for all dependencies except ensmallen. There is an rcppensmallen package in the r_test channel (https://anaconda.org/r_test/r-rcppensmallen), but that one has a conflict with some of the other packages. So I guess we have two options open a PR for rcppensmallen on conda-forge or get it into the r channel, same as r-rcpparmadillo (https://anaconda.org/conda-forge/r-rcpparmadillo). I'm not an R expert so maybe @coatless @eddelbuettel @rcurtin can provide some insights?

**Comment by eddelbuettel** [comment]
I suppose. I can't say much more as I don't use Conda myself...

**Comment by coatless** [comment]
@zoq the `r-test` channel looks like it stopped updating 10 months and 13 days ago?
https://anaconda.org/r_test

I think the `conda-forge` channel is probably where it needs to be added. That said, I'm not sure how to get `RcppEnsmallen` listed there.

**Comment by zoq** [comment]
> @zoq the `r-test` channel looks like it stopped updating 10 months and 13 days ago?
> https://anaconda.org/r_test

RIght, it's somewhat outdated.

> I think the `conda-forge` channel is probably where it needs to be added. That said, I'm not sure how to get `RcppEnsmallen` listed there.

Alright, I can open a PR on conda-forge.

**Comment by zoq** [comment]
> @zoq opened the PR on `conda-forge` for `RcppEnsmallen`.
> 
> See: [conda-forge/staged-recipes#13012](https://github.com/conda-forge/staged-recipes/pull/13012)

You are awesome.

**Comment by coatless** [comment]
@zoq conda-forge/staged-recipes#13012 was merged in. Within the next 48 hours, it should hopefully propagate onto `conda-forge` channel:

https://anaconda.org/conda-forge/r-rcppensmallen

**Comment by zoq** [comment]
Thanks a ton, it's already there.
