### ISSUE TITLE
Release script missed updating version 

### ISSUE THREAD

**Issue by coatless** [mlpack/ensmallen#240]
Looking at the release tag, the script didn't pass on the new name, version, and date information. 😭 

https://github.com/mlpack/ensmallen/blob/6f07cab7f7e6f959fe51f12c9659b627901ba229/include/ensmallen_bits/ens_version.hpp#L15-L28

**Comment by rcurtin** [comment]
I believe this is because the release PR might have been merged as a merge, not as a rebase?  @zoq do you remember how you did it?  (Anyway, when I look at the current master, the version has been changed correctly.  But most likely mlpack-bot chose to tag the wrong commit---it expects a rebase not a merge.)

**Comment by coatless** [comment]
@rcurtin I think ensmallen.org also missed out on the update? 

Is there a reason for preferring a rebase over a merge?

**Comment by rcurtin** [comment]
It makes it a little easier to figure out which commit should be tagged.  With a merge commit, I have to choose which of the two parents of the merge to look back; with a rebase, I can just take the second-most-recent commit.  I'll look into the website issue.

**Comment by rcurtin** [comment]
Website fixed---I had failed to restart mlpack-bot on the system that runs it after some changes.

**Comment by zoq** [comment]
> I believe this is because the release PR might have been merged as a merge, not as a rebase? @zoq do you remember how you did it? (Anyway, when I look at the current master, the version has been changed correctly. But most likely mlpack-bot chose to tag the wrong commit---it expects a rebase not a merge.)

I thought I hit the rebase button, maybe I miss clicked, I guess good thing that we do a follow-up release that includes - https://github.com/mlpack/ensmallen/pull/239.

**Comment by rcurtin** [comment]
Yep, just opened #241 now which will release 2.15.1.  The automation is cool but it is not perfect... yet. :smile:

**Comment by rcurtin** [comment]
Alright, 2.15.1 released and the version looks correct. :+1:  I think I should update the mlpack-bot code to be able to handle merges too, but it's a little more tedious.  I'll see if I can find the time at some point.
