### ISSUE TITLE
Issue with running ensmallen tests

### ISSUE THREAD

**Issue by BJWiley233** [mlpack/ensmallen#243]
When trying to compile ensmallen I get issue that `lib/x86_64-linux-gnu/libarmadillo.so` needs `libhdf5.so.103`. This file is in my anaconda library and I can compile armadillo programs after setting `LD_LIBRARY_PATH=/home/user/anaconda3/lib` but cannot install ensmallen as tests fail. The only file in `lib/x86_64-linux-gnu` is `libhdf5_serial.so.103`. There is no `libhdf5.so.103`

**Comment by BJWiley233** [comment]
Seemed to install with running `make` in between calls `cmake .` and `sudo make install`.  Is this correct that we can to call `make`?  For armadillo it was just `cmake .` and `sudo make install`.  If so can you update the README?

**Comment by zoq** [comment]
`make install` will run `make` first if that hasn't be done before, so it should be the same, wondering if that is a permission issue, since you call `make install` as root. Wondering if ensmallen is picking up another armadillo installation, do you have armadillo installed outside the conda env?

**Comment by BJWiley233** [comment]
I installed Armadillo headers from source.  The issue is that installing libhdf5-103 with ubuntu is that there is no libhdf5.so.103 file.  They seem to install to a `serial` folder with links to library names like `libhdf5_serial.so.103`.  Everything works fine now and running `make` before `make install` for ensmallen.  Only issue is my gcc compiler runs out of memory when installing mlpack but that is another issue.

**Comment by zoq** [comment]
I guess you installed armadillo using conda? Do you use the conda-forge channel?

**Comment by BJWiley233** [comment]
Sorry I meant to say I installed armadillo sources  with cmake and make install from the tar.gz on their website.  Then compiling works when setting ld library to the anaconda libhdf5.so.103 and their example compiles.

**Comment by zoq** [comment]
To me it looks like the LD_LIBRARY_PATH is different between root and none root. I'll see if I can reproduce the issue, if I build armadillo from source.

**Comment by BJWiley233** [comment]
Another way I was able to make it work was to create a symbolic link for `libhdf5_serial.so.103` in the hdf5/serial/lib folder to the `libhdf5_serial.so.103` that gets installed with apt.  Then in `cmake` called for setting up build for armadillo was also pass those includes and libraries to -D.  As in `cmake -D HDF5_INCLUDE_DIRS=/usr/include/hdf5/serial -D HDF5_LIBRARIES=/usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5.so.103 .`
