### ISSUE TITLE
Initial population generation in CNE

### ISSUE THREAD

**Issue by philipp-andelfinger** [mlpack/ensmallen#247]
CNE seems to generate the initial population by adding uniform noise to the initial guess, instead of Gaussian noise as stated in the comment. 

https://github.com/mlpack/ensmallen/blob/master/include/ensmallen_bits/cne/cne_impl.hpp#L91

```
// Generate the population based on a Gaussian distribution around the given
// starting point.
std::vector<BaseMatType> population;
for (size_t i = 0 ; i < populationSize; ++i)
{
  population.push_back(arma::randu<BaseMatType>(iterate.n_rows, iterate.n_cols) + iterate);
}
```

Possibly, the intended loop body is something like:

```
population.push_back(mutationSize * arma::randn<BaseMatType>(iterate.n_rows, iterate.n_cols) + iterate);
```

**Comment by rcurtin** [comment]
I opened #258 with a quick fix. :+1:
