### ISSUE TITLE
Cannot find LAPACK library, but ARMA_USE_LAPACK is set.

### ISSUE THREAD

**Issue by shediffer** [mlpack/ensmallen#250]
Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
Configuring ensmallen 2.15.1
ARMA_USE_WRAPPER is not defined, so all dependencies of Armadillo must be manually linked.
CMake Error at CMake/FindArmadillo.cmake:195 (message):
  Cannot find LAPACK library, but ARMA_USE_LAPACK is set.  Try specifying
  LAPACK libraries manually by setting the LAPACK_LIBRARY variable.
Call Stack (most recent call first):
  CMakeLists.txt:61 (find_package)

How can I solve this problem?thanks a lot!

**Comment by conradsnicta** [comment]
@shediffer Try directly linking with libopenblas.dll, as given in the Armadillo archive (download from [here](http://arma.sourceforge.net/download.html))

      armadillo-10.2.1/examples/lib_win64/libopenblas.dll
      armadillo-10.2.1/examples/lib_win64/libopenblas.lib

**Comment by shediffer** [comment]
I still have some questions, sorry to ask so much...I use cmake-gui and vs2019 to build ensmallen,  here are the results.  There's no .dll or .lib. Is this normal? 
![image](https://user-images.githubusercontent.com/78800429/107498067-47626d80-6bce-11eb-8231-91d83db88452.png)
![image](https://user-images.githubusercontent.com/78800429/107498122-55b08980-6bce-11eb-8e2f-d65af89a7d23.png)

**Comment by rcurtin** [comment]
ensmallen is a header-only library, so no `.lib` or `.dll` will be built. :)  When you use ensmallen, you only need to include the directory of header files, and link against Armadillo. :+1:

**Comment by shediffer** [comment]
Thanks a lot.👍
