### ISSUE TITLE
missing release?

### ISSUE THREAD

**Issue by conradsnicta** [mlpack/ensmallen#254]
[ensmallen.org](https://ensmallen.org) shows that [ensmallen 2.16.0](https://ensmallen.org/files/ensmallen-2.16.0.tar.gz) is available, but the 2.16.0 release doesn't seem to show up properly at the [GH releases page](https://github.com/mlpack/ensmallen/releases).  This results in the latest release to be shown as 2.15.1 on the [GH landing page](https://github.com/mlpack/ensmallen). 

A reviewer for JMLR may hence accidentally get the wrong version.  Perhaps 2.16.0 is stuck in draft mode?

**Comment by rcurtin** [comment]
You're right, thank you!  I just forgot to unmark it from draft.  Done now. :+1:
