### ISSUE TITLE
Semantic versioning and leading zeros

### ISSUE THREAD

**Issue by rcurtin** [mlpack/ensmallen#27]
I don't have any problems with version numbers like Armadillo and I can see why this is useful, but I realized while browsing http://semver.org today that this actually violates their guidelines:

```
2. A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative
 integers, and MUST NOT contain leading zeroes. X is the major version, Y is the minor
 version, and Z is the patch version. Each element MUST increase numerically. For
 instance: 1.9.0 -> 1.10.0 -> 1.11.0.
```

In this case, I think it might be more important to go with the standard instead of needing to justify why we're doing "semantic versioning except this one bit".  Lots of tools that deal with versions have specific version functions for greater than, less than, etc., such as CMake which has `VERSION_GREATER` as a comparison operator.  Thoughts?  I would say my mild preference is to stick with the original semantic versioning scheme as written, just to avoid any confusion or need for extra documentation.

**Comment by conradsnicta** [comment]
This is why the minor version in Armadillo is always 100 or greater. (it's bounded to be between 100 to 999).  This is consistent with semver guidelines -- it simply adds a further (logical) restriction.

X.0 releases are always suspect anyway, so it's better to avoid them :)

**Comment by rcurtin** [comment]
Clearly not all brain cells were firing correctly when I opened this.  Let's just do that then, although I'd prefer to got with 10-99, since I really doubt we'll ever have more than 89 minor versions. :+1:
