### ISSUE TITLE
NES implementation

### ISSUE THREAD

**Issue by onikolskyy** [mlpack/ensmallen#280]
Is there something like Natural Evolution Strategies implemented already?
Would love to implement/use it.

**Comment by zoq** [comment]
We have an PR for NEAT in mlpack https://github.com/mlpack/mlpack/pull/1908, do you have something specific in mind?

**Comment by onikolskyy** [comment]
The idea is to implement the Natural Evolution Strategies as 

- a standalone optimization algorithm
- a method to train deep neural networks (at least in the variant proposed by OpenAI)

NES samples from a Normal Distribution and is connected to CMA-ES in terms of rank-mu update (but NES does not require backtracking of evolution paths )

Further, as mentioned earlier, OpenAI proposed a variant of NES with using a diagonal covariance matrix.
This method showed to be pretty efficient due to the possibility to parallel sampling and evaluation (only few scalar shared parameters between workers are required).

I thought it would be a nice-to have for extending the RL module in mlpack, and, with non-diagonal covariance matrix, an interesting extension of the ensmallen library

**Comment by zoq** [comment]
Absolutely, I thought you are talking about evolution strategies in general, but having an NES implementation would be great.
