### ISSUE TITLE
Framework for Multi-Objective Optimizations - II

### ISSUE THREAD

**Issue by jonpsy** [mlpack/ensmallen#282]
This would be a long-standing discussion, the goal is to discuss the return types, testing and other functionalities of MOEA(Multiobejctive evolutionary algorithm)  and how it all can seamlessly fit with the established single-objective optimizer(SOO) API.

First, let's revise the goals of an MOEA:

-  To approximate the Pareto Front  (solution set) ---- (1)
-   To have a diverse set of solution       ---- (2)

**I. Optimize and iterate**
        
- In ```Optimize()``` we return the final objective for SOO, emulated in MOO by returning ```min arma::accu``` of the objective vector.
- ```iterate``` is the optimal variable in SOO, and the first element of ```bestFront``` in MOO. Ideally, ```iterate``` should have been a vector of points because there are multiple optimal variables .

Clearly, it seems we haven't incorporated the spirit of MOEA to its full extent. A quick fix would be:

   => ```Optimize()``` should return the **variance** of the Pareto Front, this checks off (2) since it gives an idea of "diversity"
   => ```iterate``` should be set to the median of ```bestFront```.

**II.Type traits [DONE]**

We may require some additional type-traits for MOEA. For ex: ```CheckArbitrartyFunctionTypeAPI```, check if a policy function has ```Evaluate()```. We would need something like ```CheckMultiArbitraryFunctionTypeAPI```(or a shorter name),  to check for ```Evaluate()``` for each function policy using variadic template recursion.

**III. Test Metrics**

Building from our discussion from I) , we can get a scalar representation of how good our model is by using Metrics. ```Optimize``` can take a template argument for that, but that breaks the existing API.

Rather, we could use it  in ```test_function_tools.hpp```, such that ```objective``` is replaced by ```performance```, where performance is the retval of metric.

A helper function  like:
```c++ 
template <typename Metric, typename PointType>
 PointType::elem_type EvaluatePerformance(Metric metric, std::vector<PointType> solutionSet)
{  return metric.Evaluate(solutionSet); }
```
which will be used as:  #278  for more
```c++
template <typename FunctionSuiteType,
          typename MatType = arma::mat,
          typename OptimizerType = ens::NSGA2,
          typename Metric = ens::indicator::HyperVolumeIndicator>
void MultiObjectiveFunctionTest(...) 
{
   ElemType performance = EvaluatePerformance<Metric>(f.GetSolutionSet);
   MultiOptimizerTest(f, optimizer, initialPoint, expectedFront, coordinateMargin,
     performance, performanceMargin, trials);
}
```

**IV. Constraints**
#272

**Comment by jonpsy** [comment]
@zoq  I'd like to know your thoughts on Section-I. I have had some talks reg. Section-I with @rcurtin over IRC, he liked the overarching idea although he may/may-not disagree with my specifics, if you're reading this join the discussion :).

**Comment by jonpsy** [comment]
Keep open

**Comment by coatless** [comment]
@zoq can you re-open the discussion thread for multiobjective optimizers?

**Comment by zoq** [comment]
Sure thing.

**Comment by jonpsy** [comment]
**A) Callbacks**

After some [discussion](https://github.com/mlpack/examples/pull/155#discussion_r640001166) , we concluded that the callbacks aren't very flexible for MOO. Sure, ```FunctionType``` is a good substitute for ```std::tuple<FunctionTypes...>```  but there were a whole lot of other problems that came to be about. 

@zoq suggested we specialize the methods of callback functions to SFINAE out for MOO optimizers. 

For ```StepTaken()``` maybe we can do

```c++
  template<typename OptimizerType,
           typename FunctionType
           typename MatType,
           typename ObjectivesArrayType,
           typename IndicesType
           typename... CallbackTypes
           >
  static bool StepTaken(OptimizerType& optimizer,
                        FunctionType& functions,
                        MatType& coordinates,
                        ObjectivesArrayType& calculatedObjectives,
                        IndicesType& frontIndices,
                        CallbackTypes&... callbacks)
  {
            // yada yada
  }
```

Such that, if I were to implement a callback that queries Pareto Front, I can do

```c++

class QueryFront
{
   // some code
  template<typename OptimizerType,
           typename FunctionType
           typename MatType,
           typename ObjectivesArrayType,
           typename IndicesType
           >
    void StepTaken(OptimizerType&  /* optimizer */,
                             FunctionType& /* function */,
                             MatType& /* coordinates */,
                             ObjectivesArrayType& calculatedObjectives, // maybe we should append const? @zoq
                             IndicesType& frontIndices,)
    {
      arma::cube currentParetoFront{};
      if(genCounter % queryRate == 0)
       {
          currentParetoFront.resize(calculatedObjectives[0].n_rows, calculatedObjectives[0].n_cols,
            fronts[0].size());
         
          for (size_t solutionIdx = 0; solutionIdx < fronts[0].size(); ++solutionIdx)
          {
             currentParetoFront.slice(solutionIdx) =
             arma::conv_to<MatType>::from(calculatedObjectives[fronts[0][solutionIdx]]);
          }
         paretoFrontArray.push_back(currentParetoFront());
       }
      ++genCounter;
    }
     // some code
};
```

Similarly, let's discuss for other methods.

**B) Evaluate**
Apart from this, I have a question, it's said that ```Evaluate()``` in callback is  called after the objective function's ```Evaluate()```. Is it automatic or do we have to write explicitly ```Callback::Evaluate()```  after calling  ```Evaluate``` of our function(s).

Please @zoq @say4n  @coatless  Let me know your thoughts on this.

**Comment by zoq** [comment]
> B) Evaluate
Apart from this, I have a question, it's said that Evaluate() in callback is called after the objective function's Evaluate(). Is it automatic or do we have to write explicitly Callback::Evaluate() after calling Evaluate of our function(s).

That is something you have to do manually, what this meant to say is that if there is a callback it will be called right after it:

https://github.com/mlpack/ensmallen/blob/f66643e1c5f0aea8f3ff0fe6b310d0d9f9ae8209/include/ensmallen_bits/sgd/sgd_impl.hpp#L149-L150

is one example.

> After some discussion , we concluded that the callbacks aren't very flexible for MOO. Sure, FunctionType is a good substitute for std::tuple<FunctionTypes...> but there were a whole lot of other problems that came to be about.

Looks like a reasonable approach to me, as  you said the callbacks interface right now, doesn't really work for MOO and I think there is no need to use another callback function that could work but wasn't meant to be used for it.

> `ObjectivesArrayType& calculatedObjectives, // maybe we should append const? @zoq`

Yes, can't think of a callback that is going to update the calculated objectives, so better be explicit here and mark it as const.

**Comment by jonpsy** [comment]
@zoq I think the time has come for comparing NSGA-II and MOEA/D-DE.

**Comment by zoq** [comment]
Agreed, the results you showed are really exciting :+1:
