### ISSUE TITLE
character strings in version numbers

### ISSUE THREAD

**Issue by conradsnicta** [mlpack/ensmallen#29]
https://github.com/mlpack/ensmallen/blob/51dbf63a19477526914e955d677dbd3bf4c15439/include/ensmallen_bits/ens_version.hpp#L15-L17
having "RC1" in the above line will cause the following line to break:
https://github.com/mlpack/ensmallen/blob/51dbf63a19477526914e955d677dbd3bf4c15439/include/ensmallen_bits/ens_version.hpp#L26

Even if somebody processes the ENS_VERSION_PATCH macro (instead of ens::version::patch), the patch version number should still be an (unsigned) integer for consistency.

I suggest marking a release as a RC within the ENS_VERSION_NAME macro:
https://github.com/mlpack/ensmallen/blob/51dbf63a19477526914e955d677dbd3bf4c15439/include/ensmallen_bits/ens_version.hpp#L18

For example, version 2.399.1 could be marked as RC1 for a new upcoming version 2.400.0.
For example:

    cout << ens::version::as_string() << endl;
    output: 2.399.1 (2.400-RC1)

Having a fixed 3 digit number (>=100) for the minor version number offers a lot of flexibility, all while staying consistent with semantic versioning :)

(related to #27)

**Comment by rcurtin** [comment]
That's fine with me.  I committed f0fb8a5 that should be consistent here. :+1:
