### ISSUE TITLE
disable building tests by default

### ISSUE THREAD

**Issue by conradsnicta** [mlpack/ensmallen#301]
With the aim of making ensmallen more approachable (easier/faster to install), I suggest to turn off building the tests by default.

For users that want to try out ensmallen, the tests are not necessary and cause an annoying slowdown in the installation.  The tests are useful to developers of ensmallen, but they are not useful to the users of ensmallen.

A target such as "tests" or "ensmallen_tests" can be used to explicitly enable building of the tests (eg. `make ensmallen_tests`).

Related comments and PR in mlpack:
* https://github.com/mlpack/mlpack/pull/2926
* https://github.com/mlpack/mlpack/issues/2524#issuecomment-825367002

**Comment by rcurtin** [comment]
Yeah, I agree, like you pointed out we did the same for mlpack.  Any other opinions on this one?  I'm happy to put together a quick PR for it. :+1:

**Comment by zoq** [comment]
Sounds like a good idea to me as well.

**Comment by conradsnicta** [comment]
@rcurtin I suggest merging https://github.com/mlpack/ensmallen/pull/300 before the quick PR for this.  The quick PR would need to adjust the wording in README.md, ie. remove mention of tests being built as part of the installation process.

**Comment by conradsnicta** [comment]
issue resolved via https://github.com/mlpack/ensmallen/pull/303
