### ISSUE TITLE
Convert ensmallen from vcpkg to nuget and submit the package to nuget repository

### ISSUE THREAD

**Issue by shrit** [mlpack/ensmallen#311]
Hello everyone,

Currently, it is possible to download ensmallen through `vcpkg`, it might be a nice feature to have ensmallen available in `nuget` too.
I do not have a Windows machine, neither the time to maintain the conversion for subsequent versions. If anyone would like to volunteer to do this that will be wonderful.
You need to convert ensmallen package via `vcpkg export` command, then you need to submit the package to `nuget` repository via their website.
Let me know in the comment if you want to handle this or if you have any questions.

**Comment by rcurtin** [comment]
Did anything else need to happen here?  It seems like ensmallen is available from nuget now, based on mlpack#2953.

**Comment by shrit** [comment]
not really, the package is available and working, we can close it if you want

**Comment by rcurtin** [comment]
Awesome!  Thanks for getting this figured out. :)
