### ISSUE TITLE
[regression in 2.17.0] Tests aren't built

### ISSUE THREAD

**Issue by yurivict** [mlpack/ensmallen#312]
In ```2.16.2``` tests were built with ```-DBUILD_TESTS=ON```, but now in ```2.17.0``` they don't get built.

**Comment by zoq** [comment]
The option was replaced with `make ensmallen_tests` see https://github.com/mlpack/ensmallen/pull/303 for more details, I also opened https://github.com/mlpack/ensmallen/pull/313 to remove the option.

**Comment by conradsnicta** [comment]
#313 merged
