### ISSUE TITLE
tests/catch.hpp update to anticipate failure to build with glibc 2.34

### ISSUE THREAD

**Issue by emollier** [mlpack/ensmallen#321]
Good day,

#### Issue description

If I trust Graham Inggs in [Debian Bug#993513](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=993513), the test suite would be at risk to not be able to run anymore with the present version of _catch_ 2.13.4.  This is, quoting Graham, "due to MINSIGSTKSZ and SIGSTKSZ no longer being defined".  _catch_ 2.13.7, or greater, are supposed to solve that issue.  Would it be possible to update _catch2_, or to trust an appropriate version could be available in the C include path, to avoid that upcoming issue?

#### Your environment

 * version of ensmallen: 2.17.0
 * operating system: Debian Sid
 * compiler: Gcc 10.3.0
 * version of Armadillo: 10.6.2
 * any other environment information you think is relevant: note that reproducing this bug would require _glibc_ 2.34, so Debian Sid to day is not yet the right platform to reproduce the problem; current _glibc_ version in Debian Experimental is 2.33, so no rush yet.  Chances are others of the listed components will get an update before the _glibc_.

#### Steps to reproduce

One would have to attempt to build the test suite, to reproduce the issue.

#### Expected behavior

The test suite should build and run.

#### Actual behavior

The test suite is likely to fail to build with errors about undefined MINSIGSTKSZ and SIGSTKSZ with _glibc_ 2.34 and greater.

In hope this helps,
Have a nice day,  :)
Étienne.

**Comment by zoq** [comment]
Thanks for the report, opened https://github.com/mlpack/ensmallen/pull/322 to update catch to the latest version.

**Comment by conradsnicta** [comment]
#322 merged
