### ISSUE TITLE
Compiling errors ensmallen 02.18.02 using VS2019 armadillo.lib 10.08.02 and mlpack.lib 03.04.02

### ISSUE THREAD

**Issue by giofum** [mlpack/ensmallen#339]
Hello everybody!
Has anyone of you experimented this problem, or similar?
I've correctly built armadillo and mlpack, but trying to compile a mlpack example leads to this:

Gravità	Codice	Descrizione	Progetto	File	Riga	Stato eliminazione
Errore	C2672	'core::v2::meta::all': non sono state trovate funzioni in overload corrispondenti	RNNLib	d:\mlpack_build2\bin\include\mlpack\core\std_backport\algorithm.hpp	316	
Errore	C2975	'Bs': argomento di modello non valido per 'core::v2::meta::all'. Prevista espressione costante in fase di compilazione	RNNLib	d:\mlpack_build2\bin\include\mlpack\core\std_backport\algorithm.hpp	316	
Errore	C2672	'core::v2::meta::none': non sono state trovate funzioni in overload corrispondenti	RNNLib	d:\mlpack_build2\bin\include\mlpack\core\std_backport\algorithm.hpp	337	
Errore	C2975	'core::v2::meta::none': argomento di modello non valido per 'Bs'. Prevista espressione costante in fase di compilazione	RNNLib	d:\mlpack_build2\bin\include\mlpack\core\std_backport\algorithm.hpp	337	
Errore	C2672	'core::v2::meta::all': non sono state trovate funzioni in overload corrispondenti	RNNLib	d:\mlpack_build2\bin\include\mlpack\core\std_backport\algorithm.hpp	417	
Errore	C2975	'Bs': argomento di modello non valido per 'core::v2::meta::all'. Prevista espressione costante in fase di compilazione	RNNLib	d:\mlpack_build2\bin\include\mlpack\core\std_backport\algorithm.hpp	417	
Errore	C2672	'core::v2::meta::none': non sono state trovate funzioni in overload corrispondenti	RNNLib	d:\mlpack_build2\bin\include\mlpack\core\std_backport\algorithm.hpp	435	
Errore	C2975	'core::v2::meta::none': argomento di modello non valido per 'Bs'. Prevista espressione costante in fase di compilazione	RNNLib	d:\mlpack_build2\bin\include\mlpack\core\std_backport\algorithm.hpp	435	
Errore	C2672	'core::v2::meta::all': non sono state trovate funzioni in overload corrispondenti	RNNLib	d:\mlpack_build2\bin\include\mlpack\core\std_backport\algorithm.hpp	859	
Errore	C2975	'Bs': argomento di modello non valido per 'core::v2::meta::all'. Prevista espressione costante in fase di compilazione	RNNLib	d:\mlpack_build2\bin\include\mlpack\core\std_backport\algorithm.hpp	859

**Comment by shrit** [comment]
Are you using RNNLib? It is not able to find the overload for RNNlLib, we do not use this library in mlpack.

**Comment by giofum** [comment]
RNNLib is the name of my library, unfortunately probably the same of an existent one

**Comment by shrit** [comment]
May I ask how are you compiling mlpack? or did you do that already? because you are mentioning that you are compiling an example?

**Comment by zoq** [comment]
I'm not sure I can see the connection with ensmallen here, unless I missed something, can you close this issue and open it in `mlpack/mlpack` and use one of the issue templates, which asks for some additional information, that helps us a lot in figuring out what the issue could be.

**Comment by giofum** [comment]
Re: May I ask how are you compiling mlpack? or did you do that already? because you are mentioning that you are compiling an example?


At first i've generated MLPack-INSTALL.vcxproj with cmake then built it. I'm new in this kind or compiling via cmake, so i'm sure i am missing something of doing something wrong

**Comment by giofum** [comment]
Re: I'm not sure I can see the connection with ensmallen here, unless I missed something, can you close this issue and open it in mlpack/mlpack and use one of the issue templates, which asks for some additional information, that helps us a lot in figuring out what the issue could be.

ok
