### ISSUE TITLE
The example to use the constrained function

### ISSUE THREAD

**Issue by ZulunZhu** [mlpack/ensmallen#345]
I am a beginner in C++, and I am curious about the template of the constrained function. Because the examples only show how to solve the square function, I don't know what should I return in the constrained function. Can anyone provide some examples? Thank you very much.
![image](https://user-images.githubusercontent.com/27121033/170808774-9677bcdd-67d0-41f4-99b2-e95d20a63fac.png)

**Comment by zoq** [comment]
Hello, what you want to return is the `f(x)`, so the function `f` at `x`, in the example above it's `x` but without the surrounding `{}`. You can find another example here - https://github.com/mlpack/ensmallen/blob/master/include/ensmallen_bits/problems/aug_lagrangian_test_functions_impl.hpp#L55-L64

Let me know if you like me to clarify anything further.

**Comment by ZulunZhu** [comment]
> 

Thanks for your reply. I think I might have formulated the code well. But another question is, when the function is too complex, the gradient is almost can not be obtained. So I use the approximation function (f'(x) = (f(x+eps)-f(x))/eps). After the optimization, I found the gradient is not close to zero. It is really strange. Do you have other ideas to get the gradient easily?

**Comment by zoq** [comment]
If you have matlab or a similair toolbox you can use that to return the gradient -- https://www.mathworks.com/help/matlab/ref/gradient.html is just one example.
