### ISSUE TITLE
Enable HTTPS on ensmallen.org

### ISSUE THREAD

**Issue by coatless** [mlpack/ensmallen#358]
Noticed today that ensmallen.org is being served over HTTP instead of HTTPS.

Would it be possible to add an HTTPS certificate?

**Comment by rcurtin** [comment]
It does work if you access https://ensmallen.org directly; but the site configuration doesn't auto-redirect to HTTPS like mlpack.org.  One quick Apache configuration change, and it's handled.  (I wonder if there's a reason I didn't do that before?  I guess I'll find out if suddenly something breaks...)
