### ISSUE TITLE
add http://ensmallen.org to githhub repo description

### ISSUE THREAD

**Issue by conradsnicta** [mlpack/ensmallen#36]
To maximise impact, I suggest expanding the github repo description from:
    A header-only C++ library for mathematical optimization. 
to
    A header-only C++ library for mathematical optimization -- http://ensmallen.org

**Comment by zoq** [comment]
Agreed, also should we add tags as well like: optimization, optimization-algorithms?

**Comment by rcurtin** [comment]
I see someone already added the website.  I added a few tags also.  Feel free to modify/change if desired.
