### ISSUE TITLE
SCD isn't stochastic and perhaps should be called CD?

### ISSUE THREAD

**Issue by rcurtin** [mlpack/ensmallen#378]
I was looking for a coordinate descent implementation and found that we do have SCD, but the actual implementation itself isn't "stochastic" in the sense of "stochastic gradient descent".  Instead, in the setting of machine learning, this would operate on all of the points at once.

My proposal is that it would be a good idea to rename this to `CD` instead of `SCD`, and maintain `SCD` (and the current typedefs) as deprecated.  Perhaps at another time in the future we can add an actually stochastic version that operates on only a few points in the dataset at a time.

Thoughts?  Did I misunderstand why the word "stochastic" was used here?

CC: @zoq, @shikharbhardwaj

**Comment by conradsnicta** [comment]
No issues from my side.  We should probably release ensmallen 2.20 after this is resolved.  The last "proper" release was way back in April 2022, and enough notable changes have accumulated since then.

**Comment by rcurtin** [comment]
Solved by #379.
