### ISSUE TITLE
move paper source to separate repo

### ISSUE THREAD

**Issue by conradsnicta** [mlpack/ensmallen#39]
The paper sources don't serve a directly useful purpose to the users of the software.  Having a single pdf would be more useful (ie. it would be immediately viewable).

It would be good to clean this up and move the sources to a separate repo, in similar vein to the joss_paper for mlpack. As an added bonus, the modified arxiv version of the paper can be kept in the same repo.

(PS. I'm happy to do the actual moving / cleanup / etc.)

**Comment by rcurtin** [comment]
I created the empty repo https://github.com/mlpack/ensmallen_paper ; if you want to move the paper sources to there that sounds good to me. :)

**Comment by rcurtin** [comment]
Thanks!  Now the sources are all in that repository.
