### ISSUE TITLE
mlpack bits (data loading)

### ISSUE THREAD

**Issue by conradsnicta** [mlpack/ensmallen#4]
At least one of the tests uses `data::Load()` from mlpack:
`data::Load("sensing_X.csv", Xorig, true, false);`
We can replace this with direct armadillo CSV loading + transposes etc.  Example:
    
    arma::mat Xorig;
    Xorig.load("sensing_X.csv", arma::csv_ascii);
    Xorig = Xorig.t();
    ...

Any thoughts?

Related to issue  #3.

**Comment by rcurtin** [comment]
Yeah, I think that's the right thing to do here.  No need for mlpack's "nice" utilities.

**Comment by mentekid** [comment]
I can pick this up if nobody is working on it.

**Comment by conradsnicta** [comment]
I believe this is done.
