### ISSUE TITLE
Templatized `Optimize()`

### ISSUE THREAD

**Issue by rcurtin** [mlpack/ensmallen#62]
Each optimizer currently has a signature like

```
template<typename FunctionType>
void Optimize(FunctionType& f, arma::mat& coordinates);
```

but really it might be nicer if we did

```
template<typename FunctionType, typename MatType>
void Optimize(FunctionType& f, MatType& coordinates);
```

The code change should be straightforward for each optimizer but there is one main issue from my end: all the documentation as written suggests writing `FunctionType` functions with `arma::mat`.  Making that documentation fully templatized would make it harder to provide really simple examples, so I have to wonder if adding some extra section on "advanced functionality" that mentions that different types of Armadillo matrices can typically be used for optimization.  If anyone has any other ideas, feel free to propose them.

Also, it's probably worth writing at least one test for a different-precision Armadillo matrix for each optimizer, but existing tests can be easily adapted, I think.  (I suppose also that means that the `Evaluate()` and `Gradient()` for everything in `problems/` will need to be adapted, but again that too should be straightforward.)

**Comment by zoq** [comment]
> all the documentation as written suggests writing FunctionType functions with arma::mat. Making that documentation fully templatized would make it harder to provide really simple examples, so I have to wonder if adding some extra section on "advanced functionality" that mentions that different types of Armadillo matrices can typically be used for optimization. If anyone has any other ideas, feel free to propose them.

I think an extra section works just fine, would be great if we could keep the documentation/examples as simple as possible.

**Comment by conradsnicta** [comment]
I recommend not making the MatType "too flexible", as people can and will try doing silly things like feeding integer matrices to the optimisers.  We probably don't want to deal with complex types either, as (based on experience) that can complicate a lot of the code.  That leaves only two viable element types: float and double.

One way to place the restriction is to first modify the signature for Optimize() et al to something like:

    template<typename FunctionType, typename eT>
    void Optimize(FunctionType& f, Mat<eT>& coordinates);

The type restriction can then be placed on the output type of the function:

    template<typename FunctionType, typename eT>
    typename arma::enable_if2< arma::is_real<eT>::value, void>::result
    Optimize(FunctionType& f, Mat<eT>& coordinates);

... or as a dummy argument:

    template<typename FunctionType, typename eT>
    void
    Optimize(FunctionType& f, Mat<eT>& coordinates, const typename arma::arma_real_only<eT>::result* junk = 0);

The above examples use internal Armadillo functionality, so I recommend adapting them to use standard C++11 approaches for type restriction.

**Comment by conradsnicta** [comment]
>  all the documentation as written suggests writing FunctionType functions with arma::mat. Making that documentation fully templatized would make it harder to provide really simple examples

In the Armadillo [documentation](http://arma.sourceforge.net/docs.html#Mat) I worked around this by stating: 

> In this documentation the _mat_ type is used for convenience; it is possible to use other types instead, eg. _fmat_

Maybe have the following in the ensmallen documentation:

> ensmallen can use either the [`mat`](http://arma.sourceforge.net/docs.html#Mat) or [`fmat`](http://arma.sourceforge.net/docs.html#Mat)  matrix types, allowing the user to use either double or single precision floating point elements. In this documentation the _mat_ type is used for convenience, and can be replaced by _fmat_.

**Comment by conradsnicta** [comment]
> Actually I would suggest the use of a `static_assert()`. SFINAE is nice and it works, but if SFINAE fails the error messages can be horrendous.

True.  However, I recommend making sure that compilers actually properly crap out and stop at the static_assert(), instead of trying to instantiate half the library anyway.  I've had experience with template code where compilation continued even though fatal errors were present.  Perhaps the compiler writers were misguidedly thinking that it would be useful to expose as many bugs in one hit as possible.

> I also think it's important to try and provide as much flexibility as we can.

That's a double edged sword, which can cut pretty deep.  For starters (and simplicity), I suggest allowing "float" and "double".  Then expand slowly to other types if the need arises.

**Comment by rcurtin** [comment]
With #119 merged, this is now solved.  Hooray!  We can release ensmallen 2.10.0 with the new support.
