### ISSUE TITLE
Additional optimizers of differentiable functions

### ISSUE THREAD

**Issue by lukasmack0** [mlpack/ensmallen#68]
Are there any optimizers that anyone would like to see implemented? In particular optimizers for differentiable functions.
@zoq any ideas or requests? @rcurtin has suggested Nesterov's Accelerated Gradient Descent method as a potential.

**Comment by zoq** [comment]
Nesterov's Accelerated Gradient Descent  sounds like a good idea to me, ND-Adam (Normalized Direction-preserving Adam) might be an alternative.

**Comment by lukasmack0** [comment]
To clarify, for Nesterov's Accelerated Gradient Descent are you referring to the algorithm described here https://blogs.princeton.edu/imabandit/2013/04/01/acceleratedgradientdescent/, as opposed to the algorithm described here http://ruder.io/optimizing-gradient-descent/index.html#nesterovacceleratedgradient which looks like it's already implemented in sgd/update_policies/nesterov_momentum_update.hpp?

**Comment by zoq** [comment]
I was thinking about the  http://ruder.io/optimizing-gradient-descent/index.html#nesterovacceleratedgradient which as you pointed out is already implemented.

**Comment by rcurtin** [comment]
@lukasmack0 I was porting mlpack issues to ensmallen today and opened #73, which I think might be interesting to you.  :+1:

**Comment by originalsouth** [comment]
> Are there any optimizers that anyone would like to see implemented? In particular optimizers for differentiable functions.

How about Non-linear Conjugate Gradient, BFGS, and perhaps even Newton--Raphson (if the Hessian is available).

**Comment by niteya-shah** [comment]
@rcurtin can I do AdamWR / SGDWR ? I read the paper and I think I can do it and I didnt see its implementation in the library.

**Comment by rcurtin** [comment]
@niteya-shah: sure, I think it could be nice to add those also.

**Comment by originalsouth** [comment]
Sad :(

**Comment by rcurtin** [comment]
We can reopen it if you like.  It might be better to open issues written for first-time contributors for BFGS, nonlinear CG, and N-R (although we don't have any abstractions for second-order differentiable functions at the moment).  We could mark those `keep-open`.  This repository doesn't currently have problems with way too many issues open, so it's not a problem for me to add a few feature requests there.  (Although I reserve the right to close the issue a year or two from now if nobody jumps on it.)

**Comment by lukasmack0** [comment]
I'd be interested in having it re-opened. I should have a lot more time to look at it in the next month or so.

**Comment by zoq** [comment]
Personally, I don't see the need to open an issue that asks for new optimisers in a general sense. Contributions in that or another direction are always welcome. Also, if somebody likes to see a method implemented, opening a new issue is just fine and also much appreciated.
