### ISSUE TITLE
Including "ensmallen.hpp" gives errors

### ISSUE THREAD

**Issue by favre49** [mlpack/ensmallen#76]
On including ensmallen.hpp, the included header files are unable to "find" the header files that they include, since the file paths seem wrong. This is fixed by using relative paths instead.

Sample code:
`#include "ensmallen.hpp"

int main()
{
	RosenbrockFunction f;
	arma::mat coordinates = f.GetInitialPoint();

	CNE optimizer(200, 10000, 0.2, 0.2, 0.3, 65, 0.1e-4);
	optimizer.Optimize(f, coordinates);

	return 0;
}`

Error in terminal:
In file included from ensmallen.hpp:64:0,
                 from test.cpp:1:
ensmallen_bits/ada_delta/ada_delta.hpp:19:38: fatal error: ensmallen_bits/sgd/sgd.hpp: No such file or directory
compilation terminated.

**Comment by rcurtin** [comment]
I don't necessarily have a problem if someone wants to change all the includes to be relative, but really it's a much better idea (and would more typically be done) to just ensure that the ensmallen include directory is available on the compiler include search path.  That can be done either by installing ensmallen to the system include directory or using `-I` to specify additional include directories just like @zoq suggested.

**Comment by favre49** [comment]
Thank you for your help, that fixed my problem :)

**Comment by rcurtin** [comment]
Great, glad it helped.  I'll go ahead and close this issue then. :+1:
