### ISSUE TITLE
Multimodal Optimizers

### ISSUE THREAD

**Issue by favre49** [mlpack/ensmallen#78]
Ensmallen currently lacks optimizers which are able to find multiple optima to multimodal functions. We could find multiple optima through niching or by having an implementation of Glowworm Swarm Optimization. Please let me know your thoughts on this.

**Comment by favre49** [comment]
NSGA-III seems interesting to me, i would like to work on it. Is it suitable to be added to the GSoC ideas list?

**Comment by zoq** [comment]
I don't think NSGA-III alone is enough work over the summer, but it could be part of an Multiobjective Optimization idea. Also, the ideas listed are mainly just ideas, feel free to propose anything else you think might be interesting.

**Comment by rcurtin** [comment]
I don't have a problem with multimodal optimizers, but what will the API look like?  If we do a GSoC project on it, that should definitely be a part of the proposal.
