### ISSUE TITLE
multiple inclusions of armadillo header

### ISSUE THREAD

**Issue by conradsnicta** [mlpack/ensmallen#8]
Pretty much all the sources in `ensmallen_bits` have `#include <armadillo>`.
It would probably make sense to simplify the code by doing the inclusion only once, at the top of `ensmallen.hpp`.

**Comment by zoq** [comment]
Agreed, I can take this up.

**Comment by rcurtin** [comment]
You're right that it can simplify the code if we do that, but it makes it harder for a user to include only a small part of ensmallen, e.g.

```
#include <ensmallen_bits/sgd/sgd.hpp>
```

if they only want to use SGD, for instance.  I don't have a *huge* preference either way, but it shouldn't be a problem to have the `#include <armadillo>` around.

**Comment by conradsnicta** [comment]
To keep things simple, I suggest to have `#include <ensmallen.hpp>` as the only supported way of using ensmallen within user code. Otherwise there's just too much stuff for us to worry about, both in the code and documentation.  This slows down development and adds to the maintenance burden.

If a user really only wants sgd, they're free to rip it out of the codebase themselves.

I don't think we should try to be overly flexible (ie. be everything to everyone). Having a focused and easy to use product would go a long way towards acceptance.

**Comment by rcurtin** [comment]
That's a fair point, and like I said I don't have a huge preference so I'm fine with it.  It might be useful to put a note in ensmallen.hpp that it's expected that ensmallen.hpp is the only header included to include the library.
