### ISSUE TITLE
CMAES sometimes gives runtime errors

### ISSUE THREAD

**Issue by favre49** [mlpack/ensmallen#80]
If you run CMAES with different seeds every time with the code:
`#include "ensmallen.hpp"
#include <armadillo>

int main()
{
	ens::test::RosenbrockFunction f;
	arma::mat coordinates = f.GetInitialPoint();
	arma::arma_rng::set_seed_random();
	ens::CMAES<> optimizer(0, -10, 10, 32, 200, -1);
	double value = optimizer.Optimize(f, coordinates);
	coordinates.print();
	std::cout << value;
}
`
and then executing, you sometimes get the error:

error: chol(): decomposition failed
terminate called after throwing an instance of 'std::runtime_error'
  what():  chol(): decomposition failed
Aborted (core dumped)

signifying that the cholesky decomposition in line 131 of cmaes_impl.cpp has failed.

**Comment by rcurtin** [comment]
@favre49 thanks for the report.  I think this can happen when the observed covariance matrix isn't positive definite (which can happen).  There are many possible solutions, but one might be to detect when the Cholesky decomposition fails and then add some small value to the diagonal (or alternately perform an eigendecomposition, set any negative eigenvalues to 0, and reconstruct).  However, I have no idea how this will affect the convergence of the algorithm itself, so I think there are lots of possibilities for what we could do here.  If you have any better suggestions feel free to implement them.
