### ISSUE TITLE
Installation with vcpkg

### ISSUE THREAD

**Issue by kereslas** [mlpack/ensmallen#84]
To be coherent with [mlpack vcpkg installation](https://github.com/mlpack/mlpack/issues/1727), I have made a [PR](https://github.com/Microsoft/vcpkg/pull/5421) to vcpkg project. I know ensmallen is a header-only library, but this way you install the header files in the folder Visual Studio looks for libraries automatically. To install it, if you have vcpkg installed, just type:

.\vcpkg install ensmallen:x64-windows

This will download, build and install the library with one command.

**Comment by rcurtin** [comment]
@kereslas thanks again, I think the right thing to do is to update the website documentation.  I'll do this when I have a chance and then we can close this issue. :+1:

**Comment by rcurtin** [comment]
Hey @kereslas, I let this sit for too long and the change is really simple.  In any case I finally got it added to a list under `download`: https://ensmallen.org/.  As ensmallen becomes available in more repositories, I'll add those instructions to the website also.  Thanks for taking the time to package it for vcpkg. :+1:
