### ISSUE TITLE
expand LogisticRegression and add GaussianDistribution

### ISSUE THREAD

**Issue by conradsnicta** [mlpack/ensmallen#9]
Many of the tests rely on functions in the LogisticRegression class that are currently not present in ensmallen. For example, `ada_delta_test.cpp` uses `LogisticRegression::ComputeAccuracy()`.  I think it's necessary to port these from mlpack in order to keep the tests working.  (It would also be quicker than rewriting the tests).

In the same vein, many tests also rely on `GaussianDistribution`, which is also currently not present in ensmallen. I had a look at the implementation in mlpack, and it shouldn't be too difficult to port it over to ensmallen. A few parts need to be rewritten, to avoid calling into other innards of mlpack.  For example, `mlpack/src/mlpack/core/dists/gaussian_distribution.cpp` calls `gmm::PositiveDefiniteConstraint::ApplyConstraint()`.
Stuff like `GaussianDistribution::serialize()` can presumably be simply stripped out.

@zoq - Since you're more familiar with the mlpack code base than me, could you port GaussianDistribution and/or the necessary functions to LogisticRegression?

**Comment by conradsnicta** [comment]
Good points.  I can take this up again tomorrow (in about 12 hours or so), unless I get beaten to it.

**Comment by zoq** [comment]
Added with https://github.com/mlpack/ensmallen/commit/f0570c82fdd4ab24cf8a5649a7564be1da97f893

**Comment by rcurtin** [comment]
This seems done now. :+1:
