### ISSUE TITLE
Source Code for Demo/Visualizations

### ISSUE THREAD

**Issue by diego898** [mlpack/ensmallen#99]
How were the visualizations done for this interactive demo?

https://vis.ensmallen.org/

Is the source available?

**Comment by zoq** [comment]
The repo (https://github.com/zoq/optimizer-visualization) doesn't contain the code for the website, but if there is interest I can push that one as well.

**Comment by diego898** [comment]
Hey @zoq - I really enjoyed the interactive figures/demos. Reminded me of distill.pub

**Comment by CastellanLiu** [comment]
> The repo (https://github.com/zoq/optimizer-visualization) doesn't contain the code for the website, but if there is interest I can push that one as well.

Dear Marcus @zoq , is it possible to share the source code for https://vis.ensmallen.org/ or to get it working again? It's a really fancy tool for understanding optimizers.
